name: Publish 3.8 Tag to DockerHub

on:
  push:
    branches:    
      - main     

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}          
      -
        name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache-3.8
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-            
      -
        name: Build and push 3.8 tag
        uses: docker/build-push-action@v2
        with:
          context: ./3.8/
          push: true
          platforms: linux/amd64,linux/arm64
          tags: docker.io/mbe1224/python-ci-tools:3.8
          cache-from: type=local,src=/tmp/.buildx-cache-3.8
          cache-to: type=local,dest=/tmp/.buildx-cache-3.8-new,mode=max
      -
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache-3.8
          mv /tmp/.buildx-cache-3.8-new /tmp/.buildx-cache-3.8       