name: Publish Tag 3.6 to DockerHub

on:
  push:
    # paths:
    #   - '3.6/**'      

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          buildkitd-flags: --debug
      -
        name: Set up containerd
        uses: crazy-max/ghaction-setup-containerd@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./3.6/
          platforms: linux/amd64,linux/arm64
          tags: docker.io/mbe1224/python-ci-tools:3.6
          outputs: type=oci,dest=/tmp/image.tar
      -
        name: Import image in containerd
        run: |
          sudo ctr i import --base-name docker.io/mbe1224/python-ci-tools --digests --all-platforms /tmp/image.tar
      -
        name: Push image with containerd
        run: |
          sudo ctr --debug i push --user "${{ secrets.DOCKER_HUB_USERNAME }}:${{ secrets.DOCKER_HUB_TOKEN }}" docker.io/mbe1224/python-ci-tools:3.6          
