name: Publish 3.6 and 3.6-alpine Tags to DockerHub

on:
  push:
    branches:    
      - main     

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}        
      -
        name: Build and push 3.6
        uses: docker/build-push-action@v2
        with:
          context: ./3.6/
          push: true
          platforms: linux/amd64,linux/arm64
          tags: docker.io/mbe1224/python-ci-tools:3.6
      -
        name: Build and push 3.6-alpine
        uses: docker/build-push-action@v2
        with:
          context: ./3.6-alpine/
          push: true
          platforms: linux/amd64,linux/arm64
          tags: docker.io/mbe1224/python-ci-tools:3.6-alpine